---
- name: tmsh modify auth user admin shell bash
  hosts: f5-bigiq
  gather_facts: False
  vars_files:
    - /ansible/inventory/group_vars/bigiq-global.yml
  tasks:
    - name: tmsh modify auth user admin shell bash
      raw: bash -c "tmsh echo -en "{{ bigiq_onboard_new_admin_password }}\n{{ bigiq_onboard_new_admin_password }}\n" | tmsh modify auth password admin; tmsh save sys config"
      ignore_unreachable: yes

    - name: tmsh modify auth user admin shell bash
      raw: bash -c "tmsh modify auth user admin shell bash; tmsh save sys config"
      ignore_unreachable: yes
