bigiq_onboard_password: admin
bigiq_onboard_new_root_password: default
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: admin
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4
bigiq_onboard_dns_search:
  - example.com
bigiq_onboard_ntp_servers:
  - time.nist.gov
bigiq_onboard_timezone: America/Los_Angeles

## Enable basic auth
bigiq_onboard_set_basic_auth: true

### Force re-running the role
bigiq_onboard_force: false

register_dcd_cm_user: admin
register_dcd_cm_password: admin
register_dcd_dcd_user: admin
register_dcd_dcd_password: admin
# List of services to activate for data collection.
register_dcd_dcd_services:
  - asm
#  - afm
#  - access
#  - dos
#  - ipsec
#  - websafe