bigiq_onboard_password: admin
bigiq_onboard_new_root_password: default
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: admin
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4
bigiq_onboard_dns_search:
  - example.com
bigiq_onboard_ntp_servers:
  - time.nist.gov
bigiq_onboard_timezone: America/Los_Angeles

register_dcd_cm_user: admin
register_dcd_cm_password: admin
register_dcd_dcd_user: admin
register_dcd_dcd_password: admin
register_dcd_dcd_services:
  - asm
#  - afm
#  - access
#  - dos
#  - ipsec
#  - websafe